### ISSUE TITLE
How-to guide for AWS DynamoDB

### ISSUE THREAD

**Issue by dray92** [devzero-inc/product-docs#49]
To merge into `branch:staging`: https://github.com/devzero-inc/product-docs/tree/staging
Expected location: https://github.com/devzero-inc/product-docs/tree/staging/how-to-guides/cloud-services/aws

Background: see other AWS how-to guides

Goal: 
- Create a recipe and build a workspace on devzero.io/dashboard
- Ensure that workspace (and any running process inside it) can communicate w/ DynamoDB

Acceptance criteria:
- PR with complete docs page (incl. all image assets; .png preferred w/ support for light/dark mode)
- Bonus points for video at the end (if through Algora, $50 tip for a good 720p+ video tutorial covering this guide)

**Comment by mishushakov** [comment]
On staging already
